---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: backend
  labels:
    build: backend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'backend:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/kirikae/demo-quote-gen.git'
      ref: master
    contextDir: quotegen
  triggers: []
  runPolicy: Serial