kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: backend-pipeline
  labels:
    build: backend-pipeline
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2  
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: https://github.com/kirikae/demo-tekton.git       
      ref: main
    contextDir: jenkins
  runPolicy: Serial